[project]
name = "bnf-impact"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "nbformat>=5.11.1",
    "pandas>=3.0.5",
    "playwright>=1.62.0",
    "plotly>=7.1.0",
    "pydantic>=2.13.5",
    "pymupdf>=1.28.2",
    "pypdf>=6.18.0",
    "requests>=2.34.2",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "toml>=0.10.2",
    "yfinance>=1.7.0",
]
